collections:
  - name: "environmental-compliance-label"
    label: "ðŸŒ² ENVIRONMENTAL COMPLIANCE"
    folder: "content/src"
    fields:
      - { name: "" }

  - name: "environmental-compliance-section"
    label: "Env Comp - Config"
    files:
      - label: "Environment Questionnaire Tasks"
        name: "env-questionnaire-task"
        file: content/src/fieldConfig/env-questionnaire.json
        editor:
          preview: false
        fields:
          - label: Questionnaire Page Config
            name: envQuestionPage
            collapsed: false
            widget: object
            fields:
              - label: Generic
                name: generic
                collapsed: true
                widget: object
                fields:
                  - { label: Title, name: title, widget: text }
                  - { label: Question, name: question, widget: string }
                  - { label: Starting Button Text, name: startingButtonText, widget: string }
                  - { label: Button Text, name: buttonText, widget: string }
                  - { label: Back Button Text, name: backButtonText, widget: string }
                  - { label: Ending Button Text, name: endingButtonText, widget: string }
                  - { label: Error Text, name: errorText, widget: string }
                  - {
                      label: Aria Context Inline Dialog Inactive,
                      name: ariaContextInlineDialogInactive,
                      widget: string,
                    }
                  - {
                      label: Aria Context Inline Dialog Active,
                      name: ariaContextInlineDialogActive,
                      widget: string,
                    }
                  - {
                      label: Aria Context Env Stepper Labels,
                      name: ariaContextEnvStepperLabels,
                      widget: string,
                    }
                  - { label: Footer, name: footerText, widget: markdown }
              - label: Instructions
                name: instructions
                collapsed: true
                widget: object
                fields:
                  - { label: Instructions Line One, name: lineOne, widget: string }
                  - { label: Instructions Line Two Part One, name: lineTwoPtOne, widget: string }
                  - { label: Instructions Line Two Not Text, name: lineTwoNotText, widget: string }
                  - { label: Instructions Line Two Part Two, name: lineTwoPtTwo, widget: string }
                  - { label: Instructions Line Three, name: lineThree, widget: string }
              - label: Waste
                name: waste
                collapsed: true
                widget: object
                fields:
                  - { label: Media Area Text, name: mediaAreaText, widget: string }
                  - { label: Media Area Link, name: mediaAreaLink, widget: markdown }
                  - label: Waste Questionnaire Options
                    name: questionnaireOptions
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Transport Waste Option, name: transportWaste, widget: text }
                      - {
                          label: Hazardous Medical Waste Option,
                          name: hazardousMedicalWaste,
                          widget: text,
                        }
                      - { label: Compost Waste Option, name: compostWaste, widget: text }
                      - { label: Treat Process Waste Option, name: treatProcessWaste, widget: text }
                      - {
                          label: Construction Debris Option,
                          name: constructionDebris,
                          widget: text,
                        }
                      - { label: No Waste Option, name: noWaste, widget: text }
              - label: Land
                name: land
                collapsed: true
                widget: object
                fields:
                  - { label: Media Area Text, name: mediaAreaText, widget: string }
                  - { label: Media Area Link, name: mediaAreaLink, widget: markdown }
                  - label: Land Questionnaire Options
                    name: questionnaireOptions
                    collapsed: true
                    widget: object
                    fields:
                      - {
                          label: Take Over Existing Business,
                          name: takeOverExistingBiz,
                          widget: text,
                        }
                      - { label: Property Assessment, name: propertyAssessment, widget: text }
                      - {
                          label: Construction Activities,
                          name: constructionActivities,
                          widget: text,
                        }
                      - {
                          label: Site Improvement Waste Land,
                          name: siteImprovementWasteLands,
                          widget: text,
                        }
                      - { label: No Land Option, name: noLand, widget: text }
              - label: Air
                name: air
                collapsed: true
                widget: object
                fields:
                  - { label: Media Area Text, name: mediaAreaText, widget: string }
                  - { label: Media Area Link, name: mediaAreaLink, widget: markdown }
                  - label: Air Questionnaire Options
                    name: questionnaireOptions
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Emit Pollutants, name: emitPollutants, widget: text }
                      - { label: Emit Emissions, name: emitEmissions, widget: text }
                      - {
                          label: Construction Activities,
                          name: constructionActivities,
                          widget: text,
                        }
                      - { label: No Air Option, name: noAir, widget: text }
              - label: Drinking Water
                name: drinkingWater
                collapsed: true
                widget: object
                fields:
                  - { label: Media Area Text, name: mediaAreaText, widget: string }
                  - { label: Media Area Link, name: mediaAreaLink, widget: string }
                  - label: Drinking Water Questionnaire Options
                    name: questionnaireOptions
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Own Well, name: ownWell, widget: string }
                      - {
                          label: Combined Well Capacity,
                          name: combinedWellCapacity,
                          widget: string,
                        }
                      - { label: Well Drilled, name: wellDrilled, widget: string }
                      - { label: Potable Water, name: potableWater, widget: string }
                      - { label: No Drinking Water, name: noDrinkingWater, widget: string }
              - label: Waste Water
                name: wasteWater
                collapsed: true
                widget: object
                fields:
                  - { label: Media Area Text, name: mediaAreaText, widget: string }
                  - { label: Media Area Link, name: mediaAreaLink, widget: string }
                  - label: Waste Water Questionnaire Options
                    name: questionnaireOptions
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Sanitary Waste, name: sanitaryWaste, widget: string }
                      - { label: Industrial Waste, name: industrialWaste, widget: string }
                      - { label: Local Sewage, name: localSewage, widget: string }
                      - { label: Septic System, name: septicSystem, widget: string }
                      - {
                          label: Streams,
                          Rivers,
                          or Lakes,
                          name: streamsRiversOrLakes,
                          widget: string,
                        }
                      - { label: Needs Treatment, name: needsTreatment, widget: string }
                      - { label: Planning Construction, name: planningConstruction, widget: string }
                      - { label: Storm Water Discharge, name: stormWaterDischarge, widget: string }
                      - {
                          label: Takeover Industrial Storm Water Permit,
                          name: takeoverIndustrialStormWaterPermit,
                          widget: string,
                        }
                      - { label: No Waste Water, name: noWasteWater, widget: string }
          - label: Results Page Config
            name: envResultsPage
            collapsed: false
            widget: object
            fields:
              - { label: Title, name: title, widget: text }
              - { label: Edit Info, name: editInfo, widget: string }
              - { label: Edit Text, name: editText, widget: string }
              - label: Summary
                name: summary
                collapsed: true
                widget: object
                fields:
                  - { label: Summary Text Pt.1, name: partOne, widget: string }
                  - { label: Summary Text Pt.2, name: partTwo, widget: string }
                  - { label: Summary Text Pt.3, name: partThree, widget: string }
                  - { label: Summary Text Pt.4, name: partFour, widget: string }
                  - label: Media Area Texts
                    name: mediaAreaText
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Waste Media Area Text, name: waste, widget: string }
                      - { label: Watershed and Land Media Area Text, name: land, widget: string }
                      - { label: Air Media Area Text, name: air, widget: string }
                      - {
                          label: Drinking Water Media Area Text,
                          name: drinkingWater,
                          widget: string,
                        }
                      - { label: Waste Water Media Area Text, name: wasteWater, widget: string }
              - label: Personalized Support
                name: personalizedSupport
                collapsed: true
                widget: object
                fields:
                  - { label: Title, name: title, widget: text }
                  - { label: Body, name: body, widget: markdown }
                  - { label: Contact, name: contact, widget: text }
                  - { label: Direct Contact, name: directContactInfo, widget: text }
                  - { label: Submission Cadence, name: submissionCadence, widget: text }
                  - { label: Email Error, name: emailErrorText, widget: text }
                  - { label: General Error, name: generalErrorText, widget: text }
                  - { label: Email Error Alert, name: emailErrorAlertText, widget: text }
                  - { label: General Error Alert, name: generalErrorAlertText, widget: text }
                  - { label: Contact SBAP Button, name: contactSbapButton, widget: string }
                  - { label: Email Address Label, name: emailLabel, widget: string }
              - label: Contact DEP
                name: contactDep
                collapsed: true
                widget: object
                fields:
                  - { label: Title, name: title, widget: text }
                  - { label: Body, name: body, widget: text }
                  - label: Waste Details
                    name: waste
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Heading, name: heading, widget: text }
                      - { label: Link in Body, name: bodyLink, widget: text }
                      - label: Contact
                        name: contact
                        collapsed: true
                        widget: object
                        fields:
                          - { label: Phone Number, name: phone, widget: text }
                          - { label: Form, name: form, widget: text }
                  - label: Land Details
                    name: land
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Heading, name: heading, widget: text }
                      - { label: Link in Body, name: bodyLink, widget: text }
                      - label: Contact
                        name: contact
                        collapsed: true
                        widget: object
                        fields:
                          - { label: Phone Number, name: phone, widget: text }
                          - { label: Form, name: form, widget: text }
                  - label: Air Details
                    name: air
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Heading, name: heading, widget: text }
                      - { label: Link in Body, name: bodyLink, widget: text }
                      - label: Contact
                        name: contact
                        collapsed: true
                        widget: object
                        fields:
                          - { label: Phone Number Info, name: phoneInfo, widget: text }
                          - { label: Phone Number, name: phone, widget: text }
                          - { label: Email, name: email, widget: text }
                  - label: Waste Water Details
                    name: wasteWater
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Heading, name: heading, widget: text }
                      - { label: Link in Body, name: bodyLink, widget: text }
                      - label: Contact
                        name: contact
                        collapsed: true
                        widget: object
                        fields:
                          - { label: Phone Number Info, name: phoneInfo, widget: text }
                          - { label: Phone Number, name: phone, widget: text }
                          - { label: Email, name: email, widget: text }
                  - label: Drinking Water Details
                    name: drinkingWater
                    collapsed: true
                    widget: object
                    fields:
                      - { label: Heading, name: heading, widget: text }
                      - { label: Link in Body, name: bodyLink, widget: text }
                      - label: Contact
                        name: contact
                        collapsed: true
                        widget: object
                        fields:
                          - { label: Phone Number Info, name: phoneInfo, widget: text }
                          - { label: Phone Number, name: phone, widget: text }
                          - { label: Email, name: email, widget: text }
              - label: See Your Responses
                name: seeYourResponses
                collapsed: true
                widget: object
                fields:
                  - { label: Title, name: title, widget: text }
              - label: Low Applicability
                name: lowApplicability
                collapsed: true
                widget: object
                fields:
                  - { label: Summary Line 1, name: summaryLineOne, widget: text }
                  - { label: Summary Line 2, name: summaryLineTwo, widget: markdown }
                  - { label: Callout, name: callout, widget: text }
                  - { label: Callout Redo Prompt, name: calloutRedo, widget: text }
