name: CMS content integrity tests

on:
  pull_request:
    branches:
      - content-repo

jobs:
  cms-content-integrity-tests:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ vars.AWS_CRYPTO_CONTEXT_ORIGIN }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Configure and Build
        uses: ./.github/actions/configure-and-build

      - name: Run Content Integrity Tests
        run: yarn workspace @businessnjgovnavigator/api cms-integrity-tests
