name: "Deploy Content Environment"

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: content
    env:
      AWS_REGION: ${{ vars.AWS_CRYPTO_CONTEXT_ORIGIN }}
      VPC_ID: ${{ vars.VPC_ID_AWS_DEV }}
      SUBNET_ID_01: ${{ vars.SUBNET_ID_01_AWS_DEV }}
      SUBNET_ID_02: ${{ vars.SUBNET_ID_02_AWS_DEV }}
      SG_ID: ${{ vars.SG_ID_AWS_DEV }}
      STAGE: ${{ vars.STAGE_CONTENT}}
      MYNJ_PROFILE_LINK: ${{ vars.MYNJ_PROFILE_LINK_SHARED }}
      AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE:
        ${{ vars.AWS_CRYPTO_CONTEXT_TAX_ID_HASHING_PURPOSE }}
      AWS_CRYPTO_CONTEXT_TAX_ID_ENCRYPTION_PURPOSE:
        ${{ vars.AWS_CRYPTO_CONTEXT_TAX_ID_ENCRYPTION_PURPOSE }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ABC_ETP_API_KEY: ${{ secrets.ABC_ETP_API_KEY_STAGING }}
      ABC_ETP_API_ACCOUNT: ${{ secrets.ABC_ETP_API_ACCOUNT_STAGING }}
      ABC_ETP_API_BASE_URL: ${{ vars.ABC_ETP_API_BASE_URL_STAGING }}
      AB_TESTING_EXPERIENCE_B_PERCENTAGE: ${{ vars.AB_TESTING_EXPERIENCE_B_PERCENTAGE_DEV }}
      AIRTABLE_USERS_TABLE: ${{ vars.AIRTABLE_USERS_TABLE_DEV }}
      API_BASE_URL: ${{ vars.API_BASE_URL_AWS_CONTENT }}
      AUTH_DOMAIN: ${{ secrets.COGNITO_AUTH_DOMAIN_CONTENT }}
      AWS_CRYPTO_CONTEXT_ORIGIN: ${{ vars.AWS_CRYPTO_CONTEXT_ORIGIN }}
      AWS_CRYPTO_CONTEXT_STAGE: ${{ vars.AWS_CRYPTO_CONTEXT_STAGE_DEV }}
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}

      BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
      BASIC_AUTH_USERNAME: ${{ vars.BASIC_AUTH_USERNAME }}
      BUSINESS_NAME_BASE_URL: ${{ vars.BUSINESS_NAME_BASE_URL_DEV }}
      COGNITO_IDENTITY_POOL_ID: ${{ secrets.COGNITO_IDENTITY_POOL_ID_CONTENT }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID_CONTENT }}
      COGNITO_WEB_CLIENT_ID: ${{ secrets.COGNITO_WEB_CLIENT_ID_CONTENT }}

      CHECK_DEAD_LINKS: ${{ vars.CHECK_DEAD_LINKS_DEV }}
      DEV_ONLY_UNLINK_TAX_ID: ${{ vars.DEV_ONLY_UNLINK_TAX_ID_DEV }}

      DYNAMICS_ELEVATOR_SAFETY_CLIENT_ID: ${{ secrets.DYNAMICS_ELEVATOR_SAFETY_CLIENT_ID }}
      DYNAMICS_ELEVATOR_SAFETY_SECRET: ${{ secrets.DYNAMICS_ELEVATOR_SAFETY_SECRET }}
      DYNAMICS_ELEVATOR_SAFETY_TENANT_ID: ${{ secrets.DYNAMICS_ELEVATOR_SAFETY_TENANT_ID }}
      DYNAMICS_ELEVATOR_SAFETY_URL: ${{ secrets.DYNAMICS_ELEVATOR_SAFETY_URL }}

      DYNAMICS_FIRE_SAFETY_CLIENT_ID: ${{ secrets.DYNAMICS_FIRE_SAFETY_CLIENT_ID }}
      DYNAMICS_FIRE_SAFETY_SECRET: ${{ secrets.DYNAMICS_FIRE_SAFETY_SECRET }}
      DYNAMICS_FIRE_SAFETY_TENANT_ID: ${{ secrets.DYNAMICS_FIRE_SAFETY_TENANT_ID }}
      DYNAMICS_FIRE_SAFETY_URL: ${{ secrets.DYNAMICS_FIRE_SAFETY_URL }}

      DYNAMICS_HOUSING_CLIENT_ID: ${{ secrets.DYNAMICS_HOUSING_CLIENT_ID }}
      DYNAMICS_HOUSING_SECRET: ${{ secrets.DYNAMICS_HOUSING_SECRET }}
      DYNAMICS_HOUSING_TENANT_ID: ${{ secrets.DYNAMICS_HOUSING_TENANT_ID }}
      DYNAMICS_HOUSING_URL: ${{ secrets.DYNAMICS_HOUSING_URL }}

      DYNAMICS_LICENSE_STATUS_CLIENT_ID: ${{ secrets.DYNAMICS_LICENSE_STATUS_CLIENT_ID }}
      DYNAMICS_LICENSE_STATUS_SECRET: ${{ secrets.DYNAMICS_LICENSE_STATUS_SECRET }}
      DYNAMICS_LICENSE_STATUS_TENANT_ID: ${{ secrets.DYNAMICS_LICENSE_STATUS_TENANT_ID }}
      DYNAMICS_LICENSE_STATUS_URL: ${{ vars.DYNAMICS_LICENSE_STATUS_URL_PROD }}

      FEATURE_CIGARETTE_LICENSE: ${{ vars.FEATURE_CIGARETTE_LICENSE_DEV }}
      FEATURE_TAX_CLEARANCE_CERTIFICATE: ${{ vars.FEATURE_TAX_CLEARANCE_CERTIFICATE_DEV }}
      FEATURE_FORMATION_SURVEY: ${{ vars.FEATURE_FORMATION_SURVEY_DEV }}
      FEATURE_LOGIN_PAGE: ${{ vars.FEATURE_LOGIN_PAGE_DEV }}
      FEATURE_MODIFY_BUSINESS_PAGE: ${{ vars.FEATURE_MODIFY_BUSINESS_PAGE_DEV }}

      FORMATION_API_ACCOUNT: ${{ secrets.FORMATION_API_ACCOUNT_DEV }}
      FORMATION_API_KEY: ${{ secrets.FORMATION_API_KEY_DEV }}
      FORMATION_API_BASE_URL: ${{ secrets.FORMATION_API_BASE_URL_DEV }}

      GOV2GO_REGISTRATION_API_KEY: ${{ secrets.GOV2GO_REGISTRATION_API_KEY_DEV }}
      GOV2GO_REGISTRATION_BASE_URL: ${{ vars.GOV2GO_REGISTRATION_BASE_URL_DEV }}

      LICENSE_STATUS_BASE_URL: ${{ vars.LICENSE_STATUS_BASE_URL_DEV }}
      MYNJ_ROLE_NAME: ${{ vars.MYNJ_ROLE_NAME_CONTENT }}
      MYNJ_SERVICE_TOKEN: ${{ secrets.MYNJ_SERVICE_TOKEN_CONTENT }}
      MYNJ_SERVICE_URL: ${{ secrets.MYNJ_SERVICE_URL_DEV }}
      NEXT_PUBLIC_WEB_BASE_URL: ${{ vars.WEB_BASE_URL_CONTENT }}
      REDIRECT_URL: ${{ vars.REDIRECT_URL_CONTENT }}
      SHOW_DISABLED_INDUSTRIES: ${{ vars.CONTENT_SHOW_DISABLED_INDUSTRIES }}
      SMOKE_TEST_ENV: ${{ secrets.SMOKE_TEST_ENV_DEV }}
      TAX_CLEARANCE_CERTIFICATE_PASSWORD: ${{ secrets.TAX_CLEARANCE_CERTIFICATE_PASSWORD_DEV }}
      TAX_CLEARANCE_CERTIFICATE_USER_NAME: ${{ secrets.TAX_CLEARANCE_CERTIFICATE_USER_NAME_DEV }}
      TAX_CLEARANCE_CERTIFICATE_URL: ${{ secrets.TAX_CLEARANCE_CERTIFICATE_URL_DEV }}
      USE_BASIC_AUTH: ${{ vars.USE_BASIC_AUTH_DEV }}
      XRAY_REGISTRATION_STATUS_BASE_URL: ${{ secrets.XRAY_REGISTRATION_STATUS_BASE_URL_DEV }}
      AWS_CRYPTO_TAX_ID_HASHING_KEY: ${{ secrets.AWS_CRYPTO_TAX_ID_HASHING_KEY_CONTENT }}
      AWS_CRYPTO_TAX_ID_ENCRYPTION_KEY: ${{ secrets.AWS_CRYPTO_TAX_ID_ENCRYPTION_KEY_CONTENT }}
      FEATURE_EMPLOYER_RATES: ${{ vars.FEATURE_EMPLOYER_RATES_DEV }}
      INTERCOM_HASH_SECRET: ${{ secrets.INTERCOM_HASH_SECRET }}

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn

      - uses: ./.github/actions/deploy
        with:
          service_name: bfs-navigator-content
